# Generated by Django 6.0.4 on 2026-05-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_ref',
        ),
    ]
