# Generated by Django 6.0.4 on 2026-05-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_address_address_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.address'),
        ),
    ]
