# Generated by Django 6.0.4 on 2026-05-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('support_email', models.EmailField(max_length=254)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
